/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Reentrancy, ReentrancyInterface } from "../Reentrancy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "LogDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "LogWithdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610356806100206000396000f3fe6080604052600436106100295760003560e01c80635fd8c7101461002e578063d0e30db014610045575b600080fd5b34801561003a57600080fd5b5061004361004f565b005b61004d61019e565b005b60008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905060003373ffffffffffffffffffffffffffffffffffffffff16826040516100b890610274565b60006040518083038185875af1925050503d80600081146100f5576040519150601f19603f3d011682016040523d82523d6000602084013e6100fa565b606091505b505090508061010857600080fd5b60008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055503373ffffffffffffffffffffffffffffffffffffffff167f08df6cd55b7282d8ab031e61b1f36cc68f27fd8136ca8c97f0a3b7e06222fd398360405161019291906102a2565b60405180910390a25050565b346000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282546101ec91906102ec565b925050819055503373ffffffffffffffffffffffffffffffffffffffff167fe89ad522dd11083142290ca875da39a094bbae4f867e639b44b630d3106c44d33460405161023991906102a2565b60405180910390a2565b600081905092915050565b50565b600061025e600083610243565b91506102698261024e565b600082019050919050565b600061027f82610251565b9150819050919050565b6000819050919050565b61029c81610289565b82525050565b60006020820190506102b76000830184610293565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006102f782610289565b915061030283610289565b925082820190508082111561031a576103196102bd565b5b9291505056fea2646970667358221220170eed2da73c8b8903abfdc9b20dba9c5fd0f48ea51fa639501e84363dc01a5964736f6c63430008110033";

type ReentrancyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Reentrancy__factory extends ContractFactory {
  constructor(...args: ReentrancyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Reentrancy> {
    return super.deploy(overrides || {}) as Promise<Reentrancy>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Reentrancy {
    return super.attach(address) as Reentrancy;
  }
  override connect(signer: Signer): Reentrancy__factory {
    return super.connect(signer) as Reentrancy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyInterface {
    return new utils.Interface(_abi) as ReentrancyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Reentrancy {
    return new Contract(address, _abi, signerOrProvider) as Reentrancy;
  }
}
